baseURL = 'https://westminsterastro.org/'
title = "Westminster Astronomical Society"
author = "Westminster Astronomical Society"
copyright = "Westminster Astronomical Society <a class=\"text-muted text-decoration-none\" href=\"https://creativecommons.org/licenses/by/4.0/\">CC BY 4.0</a>."

timeZone = 'US/Eastern'

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

theme = 'cassiopeia'

disableHugoGeneratorInject = true
enableRobotsTXT = true
#enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
tag = "tags"
category = "categories"
program = "programs"

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[permalinks]
#  post = "/post/:title/"

[module]
[module.hugoVersion]
  extended = true
  min = "0.99.1"
  max = ""
[[module.mounts]]
  source = "assets"
  target = "assets"
[[module.mounts]]
  source = "static"
  target = "static"

[privacy]
  [privacy.youTube]
    disable = false
    privacyEnhanced = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
