# Site Params

# Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
# https://gohugo.io/templates/internal/#open-graph
# https://gohugo.io/templates/internal/#twitter-cards
# https://schema.org/Thing
# https://schema.org/Article
description = "The home of Westminster Astronomical Society"
mainMenuLogo = "/icons/site-logos.svg#wasi-blue-brand"

# For favicons
## Chrome Browser
themeColor = "#3D3E77"

# Alert
alert = false
alertDismissable = true
alertText = "An Announcement! <a class=\"alert-link stretched-link\" href=\"https://example/\">Click here</a>"

[options]
colormode = "light" # "light", "dark" or "auto"
bootStrapJs = true
breadCrumb = true
listCategoryFilter = false
listTagFilter = false
listProgramFilter = false

[share]
# Providers in desired order. Valid keys: xitter, facebook, bsky, email
providers = ["xitter", "bsky", "facebook", "email"]
