[[main]]
name = "About"
url = "about"
weight = 20
title = "About Westminster Astronomical Society"

[[main]]
name = "Events"
url = "https://nightsky.jpl.nasa.gov/events/wasi/"
weight = 20
title = "WASI Night Sky Network Calendar"

[[main]]
identifier = "observatory"
name = "Observatory"
url = "observatory"
weight = 40
title = "WASI Observatory"

[[main]]
identifier = "planetarium"
name = "Planetarium"
url = "planetarium"
weight = 50
title = "Bear Branch Planetarium"

[[main]]
identifier = "resources"
name = "Resources"
weight = 60
title = "Astronomy Resources"

[[main]]
  name = "Bear Branch Almanac"
  url = "almanac"
  weight = 5
  parent = "resources"
  title = "Sun and Moon Almanac"

[[main]]
  name = "Astronomy References"
  url = "astronomy-references"
  weight = 10
  parent = "resources"

[[main]]
  name = "Observing Resources"
  url = "observer-resources"
  weight = 20
  parent = "resources"

[[main]]
  name = "Outreach Resources"
  url = "outreach"
  weight = 30
  parent = "resources"

[[main]]
  name = "Newsletter"
  url = "/newsletter"
  weight = 40
  parent = "resources"

[[main]]
  name = "Join"
  url = "/join/"
  weight = 70
  title = "Join Westminster Astronomical Society"

[[main]]
  name = "Donate"
  url = "/support/"
  weight = 80
  title = "Donate to Westminster Astronomical Society"

[[social]]
  name = "Bsky"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='social-icon icon-bsky'><use href='/icons/social-icons.svg#bsky'/></svg>"
  url = "https://bsky.app/profile/wasi-astro.bsky.social"
  weight = 20
  title = "Contact us on Bsky"

[[social]]
  name = "Xitter"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='social-icon icon-xitter'><use href='/icons/social-icons.svg#xitter'/></svg>"
  url = "https://twitter.com/WASI_Astro/"
  weight = 30
  title = "Contact us on Xitter"

[[social]]
  name = "Youtube"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='social-icon icon-youtube'><use href='/icons/social-icons.svg#youtube'/></svg>"
  url = "https://www.youtube.com/@westminsterastronomicalsoc1858"
  weight = 40
  title = "Visit our YouTube channel"

  [[social]]
  name = "Facebook"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='social-icon icon-facebook'><use href='/icons/social-icons.svg#facebook'/></svg>"
  url = "https://www.facebook.com/groups/wasi.contact/"
  weight = 50
  title = "Visit our Facebook page"
